const mongoose = require('mongoose');

// Define the schema for currency exchange rates
const currencySchema = new mongoose.Schema({
    Date: { type: Date, required: true }, // Date of the exchange rate
    Algerian_dinar: { type: Number }, // Algerian dinar (DZD)
    Australian_dollar: { type: Number }, // Australian dollar (AUD)
    Bahrain_dinar: { type: Number }, // Bahrain dinar (BHD)
    Bolivar_Fuerte: { type: Number }, // Bolivar Fuerte (VEF)
    Botswana_pula: { type: Number }, // Botswana pula (BWP)
    Brazilian_real: { type: Number }, // Brazilian real (BRL)
    Brunei_dollar: { type: Number }, // Brunei dollar (BND)
    Canadian_dollar: { type: Number }, // Canadian dollar (CAD)
    Chilean_peso: { type: Number }, // Chilean peso (CLP)
    Chinese_yuan: { type: Number }, // Chinese yuan (CNY)
    Colombian_peso: { type: Number }, // Colombian peso (COP)
    Czech_koruna: { type: Number }, // Czech koruna (CZK)
    Danish_krone: { type: Number }, // Danish krone (DKK)
    Euro: { type: Number }, // Euro (EUR)
    Hungarian_forint: { type: Number }, // Hungarian forint (HUF)
    Icelandic_krona: { type: Number }, // Icelandic krona (ISK)
    Indian_rupee: { type: Number }, // Indian rupee (INR)
    Indonesian_rupiah: { type: Number }, // Indonesian rupiah (IDR)
    Iranian_rial: { type: Number }, // Iranian rial (IRR)
    Israeli_New_Shekel: { type: Number }, // Israeli New Shekel (ILS)
    Japanese_yen: { type: Number }, // Japanese yen (JPY)
    Kazakhstani_tenge: { type: Number }, // Kazakhstani tenge (KZT)
    Korean_won: { type: Number }, // Korean won (KRW)
    Kuwaiti_dinar: { type: Number }, // Kuwaiti dinar (KWD)
    Libyan_dinar: { type: Number }, // Libyan dinar (LYD)
    Malaysian_ringgit: { type: Number }, // Malaysian ringgit (MYR)
    Mauritian_rupee: { type: Number }, // Mauritian rupee (MUR)
    Mexican_peso: { type: Number }, // Mexican peso (MXN)
    Nepalese_rupee: { type: Number }, // Nepalese rupee (NPR)
    New_Zealand_dollar: { type: Number }, // New Zealand dollar (NZD)
    Norwegian_krone: { type: Number }, // Norwegian krone (NOK)
    Omani_rial: { type: Number }, // Omani rial (OMR)
    Pakistani_rupee: { type: Number }, // Pakistani rupee (PKR)
    Peruvian_sol: { type: Number }, // Peruvian sol (PEN)
    Philippine_peso: { type: Number }, // Philippine peso (PHP)
    Polish_zloty: { type: Number }, // Polish zloty (PLN)
    Qatari_riyal: { type: Number }, // Qatari riyal (QAR)
    Russian_ruble: { type: Number }, // Russian ruble (RUB)
    Saudi_Arabian_riyal: { type: Number }, // Saudi Arabian riyal (SAR)
    Singapore_dollar: { type: Number }, // Singapore dollar (SGD)
    South_African_rand: { type: Number }, // South African rand (ZAR)
    Sri_Lankan_rupee: { type: Number }, // Sri Lankan rupee (LKR)
    Swedish_krona: { type: Number }, // Swedish krona (SEK)
    Swiss_franc: { type: Number }, // Swiss franc (CHF)
    Thai_baht: { type: Number }, // Thai baht (THB)
    Trinidadian_dollar: { type: Number }, // Trinidadian dollar (TTD)
    Tunisian_dinar: { type: Number }, // Tunisian dinar (TND)
    UAE_dirham: { type: Number }, // U.A.E. dirham (AED)
    UK_pound: { type: Number }, // U.K. pound (GBP)
    US_dollar: { type: Number }, // U.S. dollar (USD)
    Uruguayan_peso: { type: Number }, // Uruguayan peso (UYU)
    Bolivar_Soberano: { type: Number }, // Bolivar Soberano (VES)
});

// Export the model
module.exports = mongoose.model('Currency', currencySchema);
